version: '3'
#all port number should be exposed appending 9
services:
  mariadb:
    image: mariadb
    container_name: authy-mariadb
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/mariadb.conf.d/my.cnf:ro
    ports:
      - "9306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MARIADB
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloakrw
      MYSQL_DATABASE: keycloak
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
    networks:
      - keycloak-network

  keycloak-service:
    depends_on:
      - mariadb
    image: quay.io/keycloak/keycloak:latest
    container_name: authy-keycloak
    restart: unless-stopped
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
      - DB_VENDOR=MYSQL
      - DB_ADDR=mariadb
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloakrw
      - KEYCLOAK_LOGLEVEL=DEBUG
      - PROXY_ADDRESS_FORWARDING=true
      # - DB_PORT: 9306
    ports:
      - "9080:8080"
    networks:
      - keycloak-network

#  nginx:
#    image: nginx:latest
#    container_name: authy-ngnix
#    restart: unless-stopped
#    ports:
#      - "9443:443"              #9443 is mapped with external world
#    environment:
#      - ENV=development
#    #As I want the server to be always up and running, I tell Docker that it should take care of restarting the "webserver" service when it unexpectedly shuts down.
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./ssl/localhost.crt:/etc/ssl/certs/localhost.crt:ro
#      - ./ssl/localhost.key:/etc/ssl/certs/localhost.key:ro
#      - ./proxy.conf:/etc/nginx/proxy.conf:ro
#    networks:
#      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
#    name: keycloak-network
